### ISSUE TITLE
播放动态视频文件，视频部分区域存在透明度的问题

### ISSUE THREAD

**Issue by ChiangSam** [yylive/YYEVA-iOS#3]
我在使用EVAPlayer播放一个不具备Alpha 值的视频时，发现播放器改变了视频的透明度，部分区域本应该不透明，但是却可以看到后面的背景，我期望的是背景不被看到，希望修复。

**Comment by ChiangSam** [comment]
我在使用EVAPlayer播放一个不具备Alpha 值的视频时，发现播放器改变了视频的透明度，部分区域本应该不透明，但是却可以看到后面的背景，我期望的是背景不被看到，希望修复。

**Comment by guoyabiniOS** [comment]
1.1.9解决
