### ISSUE TITLE
页面假死

### ISSUE THREAD

**Issue by ZClee128** [yylive/YYEVA-iOS#7]
在swiftui中多次唤起会出去假死

**Comment by ynot16** [comment]
是在swiftUI同一个页面上多次播放同一个视频吗？
或者可以提供下录屏？
也可以提供下假死的堆栈情况

**Comment by ynot16** [comment]
> 在swiftui中多次唤起会出去假死

是在swiftUI同一个页面上多次播放同一个视频吗？
或者可以提供下录屏？
也可以提供下假死的堆栈情况

**Comment by ZClee128** [comment]
swiftui 处理释放问题，需要手动移除才可以，已经处理好了

**Comment by ynot16** [comment]
可以更新最新版本，已经修复在swiftUI内存释放问题，可以不用手动移除
